services:

    Webonaute\DoctrineFixturesGeneratorBundle\Command\GenerateDoctrineFixtureCommand:
        tags:
            - { name: 'console.command', command: 'doctrine:generate:fixture' }
        arguments:
            - $filesystem: '@filesystem'
            - $registry: '@registry'
